### ISSUE TITLE
User can sketch on the canvas.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#1]
# Motivation

In order to build our collective canvas, users must first be able to draw on the page.

# Tasks

- [x] Configure linters
- [x] Install dependencies:
    - [x] React
    - [x] ReactDOM
    - [x] Redux
    - [x] React-redux
    - [x] Express
    - [x] Body Parser
    - [x] Dotenv
- [x] Install dev-dependencies:
    - [x] Nodemon
    - [x] Babelify
    - [x] Browserify
    - [x] Watchify
    - [x] Babel Plugin Transforms (JSX & es2015)
    - [x] Mocha
    - [x] Chai
    - [x] NYC
- [x] Create a web server
    - [x] Listen for GET requests at designated port
    - [x] Serve GET requests with static middleware
- [x] Create NPM scripts for: 
    - [x] start
    - [x] watch:server
    - [x] watch:client
- [x] Create a Canvas element that users can interact with
    - [x] Create a React class component called Canvas
    - [x] Create methods on Canvas for handling mouseDown, mouseUp, mouseMove, and mouseOut 
        events
    - [x] Use the canvas context fillRect method to draw to the canvas
    - [x] Calculate the slope between the current coordinates and last coordinates to fill in a line 
        rather than a series of dots

**Comment by danielduffield** [comment]
![screen shot 2017-08-08 at 10 22 34 am](https://user-images.githubusercontent.com/29046343/29085234-8da6ef62-7c23-11e7-9e75-3425d95b1e20.png)
