### ISSUE TITLE
Users can view a list of other online users.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#11]
# Motivation

In order to better facilitate a social experience using ConCanvas, users should be able to see who else is online and/or currently contributing to the canvas.

# Tasks

- [x] Create an OnlineUsers component
    - [x] Create a button similar to the unhide chat button
    - [x] Create a dropdown that appears when the UserList is accessed
    - [x] Set the UserList to appear in front of the chat feed on the top left of the screen
    - [x] Make the list a set height and scrollable
- [x] Create a server-managed list of users currently connected
    - [x] List should contain user socket Id and nickname
    - [x] User should remove users from the list on disconnection
