### ISSUE TITLE
User can customize their color palette.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#13]
# Motivation

To enrich the artistic experience, users should be able to choose their own custom colors using a color picker.

# Tasks

- [x] Install color picker as a dependency
- [x] Position the color picker next to the PaintSidebar color palette
- [x] Add to the store
    - [x] Add an action for selecting a custom color slot
    - [x] Add an action for selecting the custom color
    - [x] Add an action for toggling the color picker
    - [x] Add an action for loading custom colors from cookies
- [x] Add handlers to hide and show the color picker when custom colors are selected
- [x] Save custom colors in user cookies
