### ISSUE TITLE
User can save the current state of the canvas.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#15]
# Motivation

In order to preserve moments using the shared canvas, users should be able to save snapshots of the canvas at any time.

# Tasks

- [x] Create a download module
    - [x] Create a "Save Snapshot" button
    - [x] Reveal a download link upon clicking the button
    - [x] Provide the canvas data in a png by setting the href of the download link to the dataURL 
       received after converting the canvas using the toDataURL method
    - [x] Hide the download link once it's been clicked so that users know to re-click the button to get 
        an updated snapshot
