### ISSUE TITLE
Fill out the Readme.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#17]
# Motivation

To help users better understand how to run the app and what technologies the app uses, the readme should contain necessary build instructions and technologies used, as well as a short demonstration.

# Tasks

- [x] Add the build instructions to the readme file
- [x] Fill out the technologies used with version information as contained in the package.json file
- [x] Commit a gif containing the demonstration of the app
- [x] Link the gif to the readme
