### ISSUE TITLE
User can draw with other users in real time.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#2]
# Motivation

Users should be able to sketch something and then revisit the page to continue where they left off.

# Tasks

- [x] Install socket.io as a dependency
- [x] Create a link between the server and clients on a specific port
- [x] Send paint data from local canvas to server
- [x] Broadcast local canvas data to all sockets with the exception of the source
