### ISSUE TITLE
Visual Update: Chat Bar

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#20]
# Motivation

The chat bar requires a visual update to replace the current layout and facilitate a better user experience.

# Tasks

- [x] Break out the UserList component from the ChatSidebar component.
    - [x] Remove the UserList from the ChatSidebar render.
    - [x] Add UserList to the App component render.
    - [x] Move the render condition from a child div to the encompassing div of the ChatSidebar.
    - [x] Relocate the display chat button from the ChatSidebar component to the Canvas.
- [x] Display the user list only when the chat sidebar is open:
    - [x] Change the hide chat button to a display users button.
    - [x] Import Font Awesome stylesheet.
    - [x] Use the Font Awesome list icon to bring up the User list.
    - [x] Add a button to close the chat sidebar in the top right corner.
    - [x] Remove the display users button.
- [x] Remove unnecessary styling for a more minimal design.
- [x] Separate guest profiles from named profiles on the user list.
