### ISSUE TITLE
Visual Update: Allow for changing orientation of the Paint Toolbar.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#22]
# Motivation

In order to facilitate a site-wide redesign with a more minimal approach and a mobile-friendly layout, the paint toolbar needs to be moved from the side of the Canvas to the bottom.

# Tasks

- [x] Add to store:
    - [x] Add a property to the utility reducer state, corresponding to isToolbarHoriz.
    - [x] Add a handler to toggle the isToolbarHoriz property.
- [x] Refactor the PaintSidebar component:
    - [x] Delete the obsolete PaintToolbar component.
    - [x] Rename the PaintSidebar component to PaintToolbar.
    - [x] Map the isToolbarHoriz property in state to props.
    - [x] Alter the dimensions and positioning of PaintToolbar styled components using toolbar orientation.
    - [x] Replace the styling information in the stylesheet with styled components in PaintToolbar file.
- [x] Add to the UtilToolbar component:
    - [x] Create a button to toggle the toolbar orientation, with a Font Awesome icon.
    - [x] Refactor the styling of components to allow for rotation if prop disableRotation is false.
    - [x] Display in vertical orientation by default.
    - [x] Position the UtilToolbar on the left side of the canvas, opposite of the vertical paint toolbar.
