### ISSUE TITLE
Visual Update: Chat and snapshot buttons

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#23]
# Motivation

In order to foster a better user experience and a smooth transition to a mobile friendly site, the buttons that bring up the chat bar and save a snapshot should be updated to a more minimal look.

# Tasks

- [x] Redesign utility buttons:
    - [x] Create a color scheme of inactive and active utilities.
    - [x] Create a new component to hold the utility buttons.
- [x] Refactor the DownloadModule component:
    - [x] Create a download button that only activates when a snapshot is captured.
    - [x] Disable the download button when the snapshot tool is inactive or after a download.
- [x] Refactor the Canvas component:
    - [x] Normalize the spacing of components when the Chat Sidebar is open.
    - [x] Import the UtilToolbar component and add to the render.
