### ISSUE TITLE
User can revisit the page to continue sketching on the same canvas.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#3]
# Motivation

In order to preserve continuity between users, the site should save the canvas as changes are made.

# Tasks

- [x] Add a timer to the Canvas on mount that sends a POST request to the server if any changes have been made to the canvas.
- [x] Send the current canvas as JSON after converting to dataURL.
- [x] Store the most recent canvas instances in a folder on the server
- [x] Delete the oldest instance once a threshold has been reached to keep the number of saved instances consistent
- [x] Use socket id and timestamps to create uniquely name canvas instance files
- [x] Track unsaved changes in an array on the server via a socket handler event
- [x] Send the unsaved changes along with the most recent Canvas instance on socket connection
- [x] Cycle through all the marks in the unsaved changes, passing each to the paintEvent method on the Canvas object
- [x] Flush the array of unsaved changes after a new instance is received by the server
