### ISSUE TITLE
User can select multiple drawing styles.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#7]
# Motivation

Users should be able to draw with multiple colors and with various line widths.

# Tasks

- [x] Adjust the Canvas component to allow for custom line width and color
    - [x] Create new parameters for line width and color
    - [x] Add to the data emitted to the server to include line width and color
- [x] Create a side toolbar
    - [x] Add a row for line widths
    - [x] Add a row for an erase tool
    - [x] Add a color picker
- [x] Handle toolbar selections
    - [x] Set Canvas properties for lineWidth and paintColor based on user selection

**Comment by danielduffield** [comment]
![screen shot 2017-08-10 at 10 49 05 am](https://user-images.githubusercontent.com/29046343/29184021-a73041da-7db9-11e7-842f-b2a73325ec41.png)
