### ISSUE TITLE
Users can chat with other online users.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/concanvas#9]
# Motivation

In order to get a sense of how many people are contributing and to reach out to other artists, users should be able to see a list of how many people are connected and chat with them in a sidebar.

# Tasks

- [x] Create a sidebar component to house the chat feed
- [x] Create a chat box component to be rendered inside the sidebar
- [x] Use websockets to broadcast chat
- [x] Create a system to allow guests to change their name
- [x] Give users a cookie so that their name is remembered upon later visits
- [x] Assign connected guest users a special identifier using socket id
- [x] Auto load this id along with the default name GUEST for new visitors

**Comment by danielduffield** [comment]
![screen shot 2017-08-11 at 10 49 40 am](https://user-images.githubusercontent.com/29046343/29225368-d8889696-7e82-11e7-99e4-6bf56777593c.png)

**Comment by danielduffield** [comment]
![screen shot 2017-08-15 at 10 22 52 am](https://user-images.githubusercontent.com/29046343/29327370-c23c561a-81a3-11e7-97b0-ef95ffc53a8f.png)
